name: Deploy

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: deploy_playbook.yml
          directory: ./deploy
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [server]
            deploy-website@35.217.39.181
          options: --verbose
